[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.13.1"
prost = "0.13.5"
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build = "0.13.1" # Uses prost 0.13.5
